
(defpackage "CLL-UTILS"
  (:use "COMMON-LISP" "BABEL" "BASE64")
  (:export "COND*" "DECODE-=???=-WORDS"
           "PROGRESS" "SIGNAL-PROGRESS" "PROGRESS-ACTION" "PROGRESS-OPERATION"
           "PROGRESS-COMPLETION" "PROGRESS-MESSAGE" "*SIGNAL-PROGRESS*" 
           "*PROGRESSING-OPERATION*" "*PROGRESSING-ACTION*" "PROGRESS-PHASE"))
