
(defpackage "CLL-LOCAL-DATE-TIME"
  (:use "COMMON-LISP")
  (:export
    "LOCAL-DATE" "LOCAL-DATE-P" "MAKE-LOCAL-DATE" "LOCAL-DATE-YEAR"
    "LOCAL-DATE-MONTH" "LOCAL-DATE-DAY" "LOCAL-DATE-WEEKDAY" "LOCAL-DATE="
    "LOCAL-DATE/=" "LOCAL-DATE<" "LOCAL-DATE<=" "LOCAL-DATE>=" "LOCAL-DATE>"
    "LOCAL-DATE-HASH" "UNIVERSAL-TIME-TO-LOCAL-DATE" "LOCAL-DATE-TO-UNIVERSAL-TIME"
    "CURRENT-LOCAL-DATE"
    "LOCAL-TIME" "LOCAL-TIME-P" "MAKE-LOCAL-TIME" "LOCAL-TIME-HOUR" "LOCAL-TIME-MINUTE"
    "LOCAL-TIME-SECOND" "LOCAL-TIME-NANOS" "LOCAL-TIME<" "LOCAL-TIME<=" "LOCAL-TIME>"
    "LOCAL-TIME>=" "LOCAL-TIME=" "LOCAL-TIME/=" "LOCAL-TIME-HASH" "CURRENT-LOCAL-TIME"
    "LOCAL-DATE-TIME" "CURRENT-LOCAL-DATE-TIME" "UNIVERSAL-TIME-TO-LOCAL-DATE-TIME"
    "LOCAL-DATE-TIME-TO-UNIVERSAL-TIME" "LOCAL-DATE-TIME=" "LOCAL-DATE-TIME/="
    "LOCAL-DATE-TIME<" "LOCAL-DATE-TIME<=" "LOCAL-DATE-TIME>=" "LOCAL-DATE-TIME>"
    "LOCAL-DATE-TIME-HASH"
    "LOCAL-YEAR" "LOCAL-MONTH" "LOCAL-DAY" "LOCAL-WEEKDAY" "LOCAL-HOUR" "LOCAL-MINUTE"
    "LOCAL-SECOND" "LOCAL-NANOS" "LOCAL-MILLISECOND" "LOCAL-MICROSECOND" "LOCAL-NANOSECOND"
    "PRINT-LOCAL-DATE" "PRINT-LOCAL-TIME" "PRINT-LOCAL-DATE-TIME"
    "FIRST-OF-MONTH" "LAST-OF-MONTH" "PREVIOUS-MONTH" "NEXT-MONTH" "PLUS-DAYS"))

(defpackage "CLL-UTILS"
  (:use "COMMON-LISP" "BABEL" "BASE64")
  (:export "COND*" "DECODE-=???=-WORDS"
           "PROGRESS" "SIGNAL-PROGRESS" "PROGRESS-ACTION" "PROGRESS-OPERATION"
           "PROGRESS-COMPLETION" "PROGRESS-MESSAGE" "*SIGNAL-PROGRESS*" 
           "*PROGRESSING-OPERATION*" "*PROGRESSING-ACTION*" "PROGRESS-PHASE"))
