
(defpackage "CLL-SCANNER"
  (:use "COMMON-LISP" "CL-PPCRE" "SPLIT-SEQUENCE"
        "DARTS.LIB.EMAIL-ADDRESS" "DARTS.LIB.MEDIA-TYPES" "CL-DATE-TIME-PARSER" 
        "FLEXI-STREAMS" "CLL-UTILS")
  (:export "SPLIT-MESSAGE" "LOAD-MESSAGE-BLOB" "MAP-OVER-FILE-MESSAGE-BLOBS"
           "DO-FILE-MESSAGE-BLOBS" "READ-FILE-MESSAGE-BLOB"))


(defpackage "CLL-INDEXER"
  (:shadowing-import-from "DARTS.LIB.SQLITE-CONNECTION" "WITH-TRANSACTION")
  (:local-nicknames (#:neta #:darts.lib.network-address))
  (:use "COMMON-LISP" "CL-PPCRE" "SPLIT-SEQUENCE" "OPTIMA" "OPTIMA.PPCRE"
        "SQLITE" "DARTS.LIB.SQLITE-CONNECTION" "DARTS.LIB.EMAIL-ADDRESS" 
        "DARTS.LIB.TOOLS" "DARTS.LIB.MEDIA-TYPES" "CL-DATE-TIME-PARSER" 
        "ZLIB" "FLEXI-STREAMS" "CLL-UTILS"
        "CLL-SCANNER")
  (:export 
    "MSGID" "MSGIDP" 
    "MAKE-MSGID" "MSGID-HASH" "MSGID=" "MSGID<" "MSGID<=" "MSGID>=" 
    "MSGID>" "MSGID/=" "MSGID-STRING" "PARSE-MSGID" "PARSE-MSGID-LIST"
    "PARSE-DATE-TIME" "UPDATE-MESSAGE-COUNTERS"))
